#!/usr/bin/env bash
#
# Start the docker container shit

set -e -x 

USERID="$(id -u)"
GROUPID="$(id -g)"

#xhost "local:root"
#if [[ "$USERID" != "1000" ]] || [[ "$GROUPID" != "1000" ]]; then
#  echo "Warning: defaulting to semi-insecure x (userid != containerUserId)"
#  xhost "local:root"
#fi

echo "launching parsec: (u${USERID}:g${GROUPID})"
docker run -it --rm \
 --env DISPLAY \
 --env PULSE_SERVER \
47eba2cfb593 app_daemon=1
# -v /tmp/.X11-unix:/tmp/.X11-unix \
# -v "/run/user/$USERID/pulse:/run/user/1000/pulse" \
# --device /dev/dri \
# --net=host \
#47eba2cfb593 app_daemon=1
